# Generated by Django 3.2.8 on 2021-12-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.RemoveField(
            model_name='video',
            name='query',
        ),
    ]
